BigFoot/Areas/InnerCircle/Controllers/GandhijiApproveController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BigFoot;

namespace BigFoot.Areas.InnerCircle.Controllers
{
    public class GandhijiApproveController : EAIController
    {
        private BigFootEntities db = new BigFootEntities();

        // GET: InnerCircle/GandhijiApprove
        public ActionResult Index()
        {
            return View(db.UserComments.ToList().OrderByDescending(c => c.Id));
        }


        [HttpPost]
        public bool ShowHide(int id, bool update)
        {
            var user = db.UserComments.Find(id);
            if (TryUpdateModel(user))
            {
                user.IsShow = update;
                db.SaveChanges();
                return true;
            }
            return false;
        }
    }
}

BigFoot/Areas/InnerCircle/Views/GandhijiApprove/Index.cshtml
@model IEnumerable<UserComments>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<table class="table">
    <tr>
        <th>
            Lefty Details
        </th>
        
        <th>
            @Html.DisplayNameFor(model => model.Comment)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Path)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name) <br />
            @Html.DisplayFor(modelItem => item.PhoneNumber) <br />
            @Html.DisplayFor(modelItem => item.Email) <br />
        </td>
        
        <td>
            @Html.DisplayFor(modelItem => item.Comment)
        </td>
        <td>
            <img src="/Pictures/@item.Path" />
        </td>

        @if (item.IsShow == null)
        {
            <td class="col-sm-1">
                <input type="button" value="Show" class="approve btn btn-primary" data-id="@item.Id" />
            </td>
            <td class="col-sm-1">
                <input type="button" value="Hide" class="reject btn btn-danger" data-id="@item.Id" />
            </td>
        }
        else if (item.IsShow == true)
        {
            <td class="col-sm-1">
                <input type="button" value="Hide" class="reject btn btn-danger" data-id="@item.Id" />
            </td>
        }
        else if (item.IsShow == false)
        {
            <td class="col-sm-1">
                <input type="button" value="Show" class="approve btn btn-primary" data-id="@item.Id" />
            </td>
        }

    </tr>
    }

</table>

<script>
    $(document).ready(function () {

        $('.approve').on("click", function () {
            var selectedId = $(this).data("id");
            $.ajax({
                type: "POST",
                url: "@Url.Action("ShowHide", "GandhijiApprove")",
                data: { id: selectedId, update: true },
            });
            $(this).prop("disabled", true);
        });

        $('.reject').on("click", function () {
            var selectedId = $(this).data("id");
            $.ajax({
                type: "POST",
                url: "@Url.Action("ShowHide", "GandhijiApprove")",
                data: { id: selectedId, update: false }
            });
            $(this).prop("disabled", true);
        });

    });
</script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}