BigFoot/Areas/InnerCircle/Controllers/MenusController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BigFoot;

namespace BigFoot.Areas.InnerCircle.Controllers
{
    public class MenusController : EAIController
    {
        private BigFootEntities db = new BigFootEntities();

        // GET: InnerCircle/Menus
        public ActionResult Index()
        {
            return View(db.Menus.ToList());
        }

        // GET: InnerCircle/Menus/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Menus menus = db.Menus.Find(id);
            if (menus == null)
            {
                return HttpNotFound();
            }
            ViewBag.Menu = menus;
            ViewBag.SubMenus = db.SubMenus.Where(sm => sm.MenuID == id).Include(p => p.Pages).ToList();
            return View();
        }

        /// <summary>
        /// Autocomplete for the Page list dropdown
        /// </summary>
        /// <param name="term"></param>
        /// <returns></returns>
        public ActionResult AutoCompletePages(string term)
        {
            var filteredItems = db.Pages.Where(c => c.Page.Contains(term)).Select(c => new { id = c.PageID, value = c.Page});

            return Json(filteredItems, JsonRequestBehavior.AllowGet);
        }


        // POST: InnerCircle/SubMenus/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateSubMenu([Bind(Include = "SubMenuID,SubMenu,MenuID,PageID")] SubMenus subMenus)
        {
            if (ModelState.IsValid)
            {
                if (subMenus.PageID != null)
                    subMenus.smUrl = SetUrl((int)subMenus.PageID, (int)subMenus.MenuID);
                db.SubMenus.Add(subMenus);
                db.SaveChanges();
                return RedirectToAction("Details", new { id=subMenus.MenuID });
            }
            
            return View("Index");
        }

        // GET: InnerCircle/SubMenus/Edit/5
        public ActionResult EditSubMenu(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SubMenus subMenus = db.SubMenus.Find(id);
            if (subMenus == null)
            {
                return HttpNotFound();
            }
            ViewBag.MenuID = new SelectList(db.Menus, "MenuID", "Menu", subMenus.MenuID);
            return View(subMenus);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditSubMenu([Bind(Include = "SubMenuID,SubMenu,PageID,MenuID")] SubMenus subMenus)
        {
            if (ModelState.IsValid)
            {
                if (subMenus.PageID != null)
                    subMenus.smUrl = SetUrl((int)subMenus.PageID, (int)subMenus.MenuID);

                db.Entry(subMenus).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MenuID = new SelectList(db.Menus, "MenuID", "Menu", subMenus.MenuID);
            return View("Index");
        }

        // GET: InnerCircle/SubMenus/Delete/5
        public ActionResult DeleteSubMenu(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SubMenus subMenus = db.SubMenus.Find(id);
            if (subMenus == null)
            {
                return HttpNotFound();
            }
            return PartialView("ConfDeleteSubMenu",subMenus);
        }

        // POST: InnerCircle/SubMenus/Delete/5                
        public ActionResult DeleteSM(int id)
        {
            SubMenus subMenus = db.SubMenus.Find(id);
            db.SubMenus.Remove(subMenus);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        private string SetUrl(int PageID, int MenuID = 0)
        {
            string ResultStr = (MenuID > 0) ? db.Menus.Find(MenuID).Menu : "";            
            ResultStr += $"/{db.Pages.Find(PageID).Page}";

            return ResultStr.Replace(' ', '-');
        }

        // GET: InnerCircle/Menus/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: InnerCircle/Menus/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MenuID,Menu,PageID")] Menus menus)
        {
            if (ModelState.IsValid)
            {
                if (menus.PageID !=null)
                    menus.mUrl = SetUrl((int)menus.PageID,0);
                db.Menus.Add(menus);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(menus);
        }

        // GET: InnerCircle/Menus/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Menus menus = db.Menus.Find(id);
            if (menus == null)
            {
                return HttpNotFound();
            }

            

            return View(menus);
        }

        // POST: InnerCircle/Menus/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MenuID,Menu,PageID")] Menus menus)
        {
            if (ModelState.IsValid)
            {
                if (menus.PageID != null)
                    menus.mUrl = SetUrl((int)menus.PageID,0);
                db.Entry(menus).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(menus);
        }

        // GET: InnerCircle/Menus/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Menus menus = db.Menus.Find(id);
            if (menus == null)
            {
                return HttpNotFound();
            }
            return View(menus);
        }

        // POST: InnerCircle/Menus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (!db.SubMenus.Any(ms => ms.MenuID == id))
            {
                Menus menus = db.Menus.Find(id);
                db.Menus.Remove(menus);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return RedirectToAction("Delete", new { id = id }); 
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BigFoot/Areas/InnerCircle/Views/Menus/ConfDeleteSubMenu.cshtml
@model BigFoot.SubMenus

<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Are You Sure ?</h4>
            </div>

            <div class="modal-body">
                <p>You are about to delete @Model.SubMenu</p>
                <p>Note: The page (if any) that this submenu is linked to will not be deleted</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Dont Delete</button>
                <button type="button" class="btn btn-danger" data-dismiss="modal" onclick="location.href='@Url.Action("DeleteSM", new { id = Model.SubMenuID })'">Delete it</button>
            </div>


        </div>

    </div>
</div>

BigFoot/Areas/InnerCircle/Views/Menus/Create.cshtml
@model BigFoot.Menus

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Menus</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.PageID)
        <div class="form-group">
            @Html.LabelFor(model => model.Menu, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Menu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Menu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Page</label>
            <div class="col-md-10">
                <input type="text" id="Page" name="Page" style="color:black;" data-autocomplete-idholder="#PageID" data-autocombo-url='@Url.Action("AutoCompletePages")' class="form-control" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BigFoot/Areas/InnerCircle/Views/Menus/Delete.cshtml
@model BigFoot.Menus

@{
    ViewBag.Title = "Delete";
}

<h2>Delete (First ensure ALL submenus that are under this Menu item are deleted)</h2>

<h3>Are you sure you want to delete this?</h3>
    <p>Note: This action does NOT delete any underlying pages</p>
<div>
    <h4>Menus</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Menu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Menu)
        </dd>

        <dt>
            URL
        </dt>

        <dd>
            @Html.DisplayFor(model => model.mUrl)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BigFoot/Areas/InnerCircle/Views/Menus/Details.cshtml
@model BigFoot.SubMenus

@{
    ViewBag.Title = "Details";
}

<h2>SubMenu for: @ViewBag.Menu.Menu</h2>

<p>    
    @Html.ActionLink("Back to List", "Index")
</p>

<hr style="border-bottom-color:darkslategray;"/>


@using (Html.BeginForm("CreateSubMenu", "Menus", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.Hidden("MenuID", (int)ViewBag.Menu.MenuID)
    @Html.HiddenFor(model => model.PageID)
    <div class="form-horizontal">
        <h3>SubMenus</h3>
        <p>Note: Adding a submenu will cause the page (if any is set) of the main menu to be ignored</p>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.SubMenu, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SubMenu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SubMenu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Page</label>
            <div class="col-md-10">
                <input type="text" id="Page" name="Page" style="color:black;" data-autocomplete-idholder="#PageID" data-autocombo-url='@Url.Action("AutoCompletePages")' class="form-control" />                
            </div>
        </div>
        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<hr />
<h3><u>Existing SubMenus</u></h3>
<table width="80%">
    <tr>
        <th>SubMenu</th>
        <th>Page</th>
        <th></th>
    </tr>
@foreach (var sm in ViewBag.SubMenus)
{
    <tr>
        <td>@sm.SubMenu</td>
        <td>@if (sm.PageID != null)
        {  @sm.Pages.Page }
        </td> 
        <th>@Html.ActionLink("Edit","EditSubMenu", new { id = sm.SubMenuID }) |
        &nbsp; <a href="#" onclick="DeleteSM(@sm.SubMenuID)">Delete</a></th>
        
    </tr>
}
</table>

<!-- Trigger the modal with a button -->
<div id="modalWrapper">
    @* Inject form here *@
</div>



<script>
$(function() {
    $('#myModal').modal();
});

function DeleteSM(productId) {
    $.ajax({
        url: '/InnerCircle/Menus/DeleteSubMenu/'+ productId, // The method name + paramater
        success: function(data) {
            $('#modalWrapper').html(data); // This should be an empty div where you can inject your new html (the partial view)
            $('#myModal').modal();
        }
    });
}
</script>

BigFoot/Areas/InnerCircle/Views/Menus/Edit.cshtml
@model BigFoot.Menus

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Menus</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MenuID)
       

        <div class="form-group">
            @Html.LabelFor(model => model.Menu, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Menu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Menu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Page</label>
            <div class="col-md-10">
                @if (Model.PageID != null)
                {
                    @Html.HiddenFor(model => model.PageID)
                    <input type="text" value="@Model.Pages.Page" id="Page" name="Page" style="color:black;" data-autocomplete-idholder="#PageID" data-autocombo-url="@Url.Action("AutoCompletePages")" class="form-control" />
                }
                else
                {
                    @Html.Hidden("PageID")
                    <input type="text" id="Page" name="Page" style="color:black;" data-autocomplete-idholder="#PageID" data-autocombo-url="@Url.Action("AutoCompletePages")" class="form-control" />
                }

            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BigFoot/Areas/InnerCircle/Views/Menus/EditSubMenu.cshtml
@model BigFoot.SubMenus

@{
    ViewBag.Title = "Edit SubMenu of Menu: " + Model.Menus.Menu ;
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm("EditSubMenu","Menus",FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SubMenus</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.SubMenuID)
        @Html.HiddenFor(model => model.PageID)

        <div class="form-group">
            @Html.LabelFor(model => model.SubMenu, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SubMenu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SubMenu, "", new { @class = "text-danger" })
            </div>
        </div>

        

        <div class="form-group">
            @Html.LabelFor(model => model.MenuID, "MenuID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MenuID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MenuID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Page</label>
            <div class="col-md-10">
                @if (Model.Pages != null)
                {
                    <input type="text" value="@Model.Pages.Page" id="Page" name="Page" style="color:black;" data-autocomplete-idholder="#PageID" data-autocombo-url="@Url.Action("AutoCompletePages")" class="form-control" />
                } else { 
                    <input type="text" id="Page" name="Page" style="color:black;" data-autocomplete-idholder="#PageID" data-autocombo-url="@Url.Action("AutoCompletePages")" class="form-control" />
                }
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Details" , new { id = Model.MenuID })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BigFoot/Areas/InnerCircle/Views/Menus/Index.cshtml
@model IEnumerable<BigFoot.Menus>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New Menu", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Menu)
        </th>
        <th>
            SubMenus
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr style="background-color:darkslategrey; color:antiquewhite">
        <td>
            <strong>
                @Html.DisplayFor(modelItem => item.Menu)
            </strong>
        </td>
        <td>
            @if (item.PageID != null)
            {
                @Html.DisplayFor(modelItem => item.Pages.Page);
             }
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.MenuID }) |  
            @Html.ActionLink("SubMenus", "Details", new { id = item.MenuID }) |  
            @Html.ActionLink("Delete", "Delete", new { id=item.MenuID })
        </td>
    </tr>
    
    var sitems = item.SubMenus;
    
    <tr>
        <td></td>
        <td>
            <table width="70%">
            @foreach (var sitem in sitems)
            {
                <tr>
                    <td>@sitem.SubMenu</td>
                    <td>
                    @if (sitem.PageID != null)
                    {
                        @sitem.Pages.Page;
                    }
                    </td>
                </tr>
            }
            </table>
        </td>
        <td></td>
    </tr>
    }

</table>